// Code generated by protoc-gen-go.
// source: datatype.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	datatype.proto
	echo.proto
	role.proto

It has these top-level messages:
	RoleBasic
	Task
	Item
	Role
*/
package pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RoleBasic struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Occupation       *uint32 `protobuf:"varint,2,req,name=occupation" json:"occupation,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoleBasic) Reset()         { *m = RoleBasic{} }
func (m *RoleBasic) String() string { return proto.CompactTextString(m) }
func (*RoleBasic) ProtoMessage()    {}

func (m *RoleBasic) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RoleBasic) GetOccupation() uint32 {
	if m != nil && m.Occupation != nil {
		return *m.Occupation
	}
	return 0
}

func (m *RoleBasic) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Task struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Progress         *uint32 `protobuf:"varint,2,req,name=progress" json:"progress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}

func (m *Task) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Task) GetProgress() uint32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

type Item struct {
	Guid             *uint32 `protobuf:"varint,1,req,name=guid" json:"guid,omitempty"`
	Itemid           *uint32 `protobuf:"varint,2,req,name=itemid" json:"itemid,omitempty"`
	Count            *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Bag              *uint32 `protobuf:"varint,4,req,name=bag" json:"bag,omitempty"`
	Index            *uint32 `protobuf:"varint,5,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func (m *Item) GetGuid() uint32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *Item) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *Item) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Item) GetBag() uint32 {
	if m != nil && m.Bag != nil {
		return *m.Bag
	}
	return 0
}

func (m *Item) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type Role struct {
	Basic            *RoleBasic `protobuf:"bytes,1,req,name=basic" json:"basic,omitempty"`
	Tasklist         []*Task    `protobuf:"bytes,2,rep,name=tasklist" json:"tasklist,omitempty"`
	Itemlist         []*Item    `protobuf:"bytes,3,rep,name=itemlist" json:"itemlist,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}

func (m *Role) GetBasic() *RoleBasic {
	if m != nil {
		return m.Basic
	}
	return nil
}

func (m *Role) GetTasklist() []*Task {
	if m != nil {
		return m.Tasklist
	}
	return nil
}

func (m *Role) GetItemlist() []*Item {
	if m != nil {
		return m.Itemlist
	}
	return nil
}

func init() {
}
