// Code generated by protoc-gen-go.
// source: item.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Item struct {
	Guid             *uint32 `protobuf:"varint,1,req,name=guid" json:"guid,omitempty"`
	Itemid           *uint32 `protobuf:"varint,2,req,name=itemid" json:"itemid,omitempty"`
	Count            *uint32 `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
	Bag              *uint32 `protobuf:"varint,4,req,name=bag" json:"bag,omitempty"`
	Index            *uint32 `protobuf:"varint,5,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func (m *Item) GetGuid() uint32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *Item) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *Item) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Item) GetBag() uint32 {
	if m != nil && m.Bag != nil {
		return *m.Bag
	}
	return 0
}

func (m *Item) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func init() {
}
