// Code generated by protoc-gen-go.
// source: msgtype.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MsgType int32

const (
	MsgType_MQROLELIST   MsgType = 1
	MsgType_MQCREATEROLE MsgType = 2
	MsgType_MQLOGIN      MsgType = 3
	MsgType_MQECHO       MsgType = 4
	MsgType_MQLOGOUT     MsgType = 5
	MsgType_MRROLEBASIC  MsgType = 6
	MsgType_MRROLELIST   MsgType = 7
	MsgType_MRLOGIN      MsgType = 8
	MsgType_MRCREATEROLE MsgType = 9
	MsgType_MRECHO       MsgType = 10
)

var MsgType_name = map[int32]string{
	1:  "MQROLELIST",
	2:  "MQCREATEROLE",
	3:  "MQLOGIN",
	4:  "MQECHO",
	5:  "MQLOGOUT",
	6:  "MRROLEBASIC",
	7:  "MRROLELIST",
	8:  "MRLOGIN",
	9:  "MRCREATEROLE",
	10: "MRECHO",
}
var MsgType_value = map[string]int32{
	"MQROLELIST":   1,
	"MQCREATEROLE": 2,
	"MQLOGIN":      3,
	"MQECHO":       4,
	"MQLOGOUT":     5,
	"MRROLEBASIC":  6,
	"MRROLELIST":   7,
	"MRLOGIN":      8,
	"MRCREATEROLE": 9,
	"MRECHO":       10,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}

func init() {
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
}
